### ISSUE TITLE
Missing timelib_config.h

### ISSUE THREAD

**Issue by nlaplante** [derickr/timelib#1]
When running make, I get the following error:

```
In file included from timelib.h:24:0,
                 from tm2unixtime.c:21:
timelib_structs.h:24:28: fatal error: timelib_config.h: No such file or directory
 #include "timelib_config.h"
```

**Comment by martijnotto** [comment]
I have the same problem. Uncommenting the line including this file leads to a world of hurt, first of all, types like 'int32_t' aren't known to C++, which can be fixed by including stdint.h.

After this it keeps raining errors about implicit declaration of functions, which, incidentally, seem to be incompatible with the build-in functions (like realloc). I was unable to compile it in the end.

**Comment by derickr** [comment]
This should be fixed already - there is now a conditional define for it.
