### ISSUE TITLE
Support for POSIX timezone strings in "slim" files

### ISSUE THREAD

**Issue by rbro** [derickr/timelib#14]
I work with future dates often and submitted this bug where converting a timestamp to a local datetime doesn't seem to be accurate for future dates - https://bugs.php.net/bug.php?id=69806.  It seems related to Daylight Saving Time not being applied for dates after the year 2038 32-bit integer cut-off.  I just wanted to raise it as an issue as I'm running into it often working with future dates.

Thank you for your help.

**Comment by derickr** [comment]
Hi,

sorry, I missed this issue. Newer versions are aware of longer data existing (until 2499), but the library does not do anything with this data yet. Right now, it just skips over them: https://github.com/derickr/timelib/blob/master/parse_tz.c#L513

This is probably not very hard to support.

However, I would suggest that if you work with future dates, then you use UTC exclusively. There is of course no guarantee that DST stays the same in the (far) future.

cheers,
Derick

**Comment by eggert** [comment]
Please boost the priority of fixing this bug, as it can occur cven with current timestamps on NetBSD. This is because NetBSD generates its TZif files via the command 'zic -b slim', which omits the unnecessary transitions through the year 2038 that were put into tzcode 95f (1995) only for backward compatibility with older 32-bit-only software. (The zic command's '-b slim' option was added in [tzdb 2019b](https://mm.icann.org/pipermail/tz-announce/2019-July/000056.html).) On NetBSD, Europe/Amsterdam's last explicit transition is on 1996-03-31 and TZif readers are supposed to deduce later transitions from the POSIX-like TZ string ''CET-1CEST,M3.5.0,M10.5.0/3" at the end of the Europe/Amsterdam file. However, timelib ignores the TZ string and therefore mishandles many current timestamps.

For more info, please see [PHP Bug#7968](https://bugs.php.net/bug.php?id=79698). Documentation for the TZif format is in [Internet RFC 8536](https://tools.ietf.org/html/rfc8536).
