### ISSUE TITLE
Format without time sets current time

### ISSUE THREAD

**Issue by boesing** [derickr/timelib#33]
Hey guys,

just wondering why the timelib sets the current time if using the following format:

```php
$date = DateTime::createFromFormat('Y-m-d', '2018-02-05');
var_dump($date);
```

```
class DateTime#1 (3) {
  public $date =>
  string(26) "2018-02-05 15:14:58.000000"
  public $timezone_type =>
  int(3)
  public $timezone =>
  string(13) "Europe/Berlin"
}
```

Now, if I want to compare e.g. the same value against the first one after some time because I just would like to check if the date is the same, I will get weird issues:

```php
$date1 = DateTime::createFromFormat('Y-m-d', '2018-02-05');
sleep(1);
$date2 = DateTime::createFromFormat('Y-m-d', '2018-02-05');

$date1 == $date2; // false

$date1->setTime(0, 0);
$date2->setTime(0, 0);

$date1 == $date2; // true
```

I don't get the reason, why the timelib would even interpret the time value at all since none is passed to `createFromFormat` and (imho) supposed to be 0.

BTW: Sorry that I used PHP to provide examples but I guess you get what I mean.

**Comment by derickr** [comment]
It does this because it's more flexible. You can use the ``!`` character (resets everything to 1970-01-01 00:00:00) at the start of your format with ``createFromFormat`` to get the result you expect, or ``|`` at the end (resets un-parsed fields):

- https://github.com/derickr/timelib/blob/master/parse_date.re#L1961-L1962
- https://github.com/derickr/timelib/blob/master/parse_date.re#L2267-L2273
