### ISSUE TITLE
Resolve unexpected behavior with "(first | last) day of {non-month expression}"

### ISSUE THREAD

**Issue by clayliddell** [derickr/timelib#81]
## Problem

Currently whenever "first day of" or "last day of" prefixes a date time expression it will assume the user wants the first/last day of the month belonging to the following expression. This makes sense in the case of an expression such as `first day of this month` or `first day of July 2020` where the user is attempting to retrieve the first day of the corresponding month; however, since "(last | this | next) (week | year | fortnight | etc.)" are considered to be valid expressions on their own, they will provide the user with unexpected results.

### Example

If the current day is July 4th, 2020 and a user enters `first day of this year`, it will result in "July 1st, 2020" rather than the expected "January 1st, 2020".

## Proposed solution

Add support for contextually determining what unit the user is attempting to retrieve the `(first | last) day` within.

**Comment by derickr** [comment]
Hi Clay,

I just had a look at this, but this is not possible without a lot of guessing. The parser is currently context free and the phrase `first day of` is standing on its own. In order to support it for all the other combinations, I would have to add a rule to support that. There would be potentially 100s of these. And then even then, there would be an issue with `first day of this week` and `first day of this week this year` vs `first day of this year this week`.

cheers,
Derick
